Repository Shining-Jicheon-Stars/yjg-dart-flutter-frontend, pull requests merged in 2024-03, with the labels that each got.

#102 Feat: ログインユーザータイプに応じたルーティング分離
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/models/admin_service.dart
  lib/auth/data/models/user_service.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/auth/domain/usecases/register_usecase.dart
  lib/auth/presentation/pages/admin_login.dart
  lib/auth/presentation/pages/login_google_domestic_students.dart
  lib/auth/presentation/pages/student_login.dart
  lib/auth/presentation/viewmodels/login_viewmodel.dart
  lib/auth/presentation/viewmodels/privilege_viewmodel.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/auth/presentation/widgets/international_admin_login_form.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/main.dart
Labels: 🔨 Chore, 🔥 Remove, ✨ Feat, 💄 Design, ♻️ Refactor

#105 Feat: 学校のメールではないGoogleメールのログイン防止
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/domain/usecases/domain_validation_usecase.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/google_login_button.dart
Labels: 🔨 Chore, 🐛 Fix, ✨ Feat

#106 Feat: 美容室の価格表フィルターボタンUIおよび選択後の状態管理ロジックの実装
  android/app/build.gradle
  android/build.gradle
  ios/Podfile
  ios/Podfile.lock
  lib/auth/presentation/pages/international_registration.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/salon/data/models/category.dart
  lib/salon/presentaion/viewmodels/category_viewmodel.dart
  lib/salon/presentaion/viewmodels/user_selection_viewmodel.dart
  lib/salon/presentaion/widgets/filter_group_botton.dart
  lib/salon/presentaion/widgets/multi_select.dart
  lib/shared/service/auth_service.dart
  lib/shared/widgets/base_appbar.dart
  lib/shared/widgets/base_drawer.dart
Labels: 🔨 Chore, 🔥 Remove, ✨ Feat

#108 Feat: 価格表ページのAPI通信ロジック作成
  lib/as(admin)/presentation/pages/as_main.dart
  lib/salon(admin)/presentation/pages/admin_salon_main.dart
  lib/salon/data/data_sources/price_data_source.dart
  lib/salon/data/models/service.dart
  lib/salon/presentaion/pages/salon_price_list.dart
  lib/salon/presentaion/viewmodels/service_viewmodel.dart
  lib/salon/presentaion/viewmodels/user_selection_viewmodel.dart
  lib/salon/presentaion/widgets/filter_group_botton.dart
  lib/salon/presentaion/widgets/filter_service_list.dart
Labels: 🔥 Remove, ✨ Feat, 💄 Design

#109 Feat: お知らせページAPI接続
  android/app/build.gradle
  lib/administration/presentaion/pages/notice.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feat

#110 Feat: 外出/外泊申請ページAPI接続
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/administration/presentaion/widgets/sleepover_widget.dart
Labels: ✨ Feat

#114 Feat: 美容室予約ページおよび私の予約確認ページのAPI通信ロジックの実装
  lib/administration/presentaion/pages/notice.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/dashboard/presentaion/pages/dashboard_main.dart
  lib/dashboard/presentaion/widgets/rounded_box.dart
  lib/main.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
  lib/salon/data/data_sources/booking_data_source.dart
  lib/salon/data/data_sources/my_booking_data_source.dart
  lib/salon/data/data_sources/price_data_source.dart
  lib/salon/data/models/business_hours.dart
  lib/salon/data/models/reservation.dart
  lib/salon/domain/entities/ reservation.dart
  lib/salon/domain/usecases/reservation_usecase.dart
  lib/salon/presentaion/pages/salon_booking.dart
  lib/salon/presentaion/pages/salon_booking_step_one.dart
  lib/salon/presentaion/pages/salon_booking_step_two.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/salon/presentaion/pages/salon_my_book.dart
  lib/salon/presentaion/viewmodels/booking_business_hours_viewmodel.dart
  lib/salon/presentaion/viewmodels/booking_select_id_viewmodel.dart
  lib/salon/presentaion/viewmodels/booking_select_list_viewmodel.dart
  lib/salon/presentaion/viewmodels/reservations_viewmodel.dart
  lib/salon/presentaion/viewmodels/service_viewmodel.dart
  lib/salon/presentaion/widgets/alert_button.dart
  lib/salon/presentaion/widgets/booking_calendar.dart
  lib/salon/presentaion/widgets/booking_execution_modal.dart
  lib/salon/presentaion/widgets/booking_next_button.dart
  lib/salon/presentaion/widgets/booking_next_modal.dart
  lib/salon/presentaion/widgets/booking_select_timeline.dart
  lib/salon/presentaion/widgets/booking_service_button.dart
  lib/salon/presentaion/widgets/booking_service_select.dart
  lib/salon/presentaion/widgets/date_button.dart
  lib/salon/presentaion/widgets/my_booking_list.dart
  lib/salon/presentaion/widgets/my_booking_modal.dart
  lib/salon/presentaion/widgets/service_tabbar.dart
  lib/salon/presentaion/widgets/time_slots_grid.dart
  lib/shared/widgets/white_main_rounded_box.dart
Labels: 🐛 Fix, ✨ Feat, 💄 Design, ♻️ Refactor

#115 Rename: ファイル名の修正
  lib/salon/domain/entities/reservation.dart
Labels: 🚚 Rename

#116 Refactor: APIトークンの設定
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/administration/presentaion/widgets/sleepover_widget.dart
Labels: ♻️ Refactor

#124 Refactor: Token関連のモデル修正
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/models/admin_service.dart
  lib/auth/data/models/token_response.dart
  lib/auth/presentation/viewmodels/privilege_viewmodel.dart
  lib/auth/presentation/viewmodels/user_viewmodel.dart
  pubspec.lock
  pubspec.yaml
Labels: ♻️ Refactor

#126 Refactor: APIトークンの変更
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/administration/presentaion/widgets/sleepover_widget.dart
Labels: ♻️ Refactor

#127 Feat: ASページAPI接続
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/as_application.dart
  lib/administration/presentaion/pages/as_page.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/as(admin)/presentation/pages/as_main.dart
  lib/shared/widgets/as_card.dart
  lib/shared/widgets/as_image_view.dart
Labels: ✨ Feat

#128 Fix: AS日付修正時のエラー修正
  lib/as(admin)/presentation/pages/as_detail.dart
Labels: 🐛 Fix

#129 Refactor: 特定の日付の営業時間を読み込むようにAPIをリファクタリング
  ios/Podfile.lock
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/domain/entities/user.dart
  lib/auth/presentation/viewmodels/user_viewmodel.dart
  lib/main.dart
  lib/salon/data/data_sources/booking_data_source.dart
  lib/salon/data/data_sources/notice_data_source.dart
  lib/salon/data/models/business_hours.dart
  lib/salon/data/models/notice.dart
  lib/salon/domain/usecases/reservation_usecase.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/salon/presentaion/viewmodels/booking_business_hours_viewmodel.dart
  lib/salon/presentaion/viewmodels/booking_select_list_viewmodel.dart
  lib/salon/presentaion/viewmodels/notice_viewmodel.dart
  lib/salon/presentaion/widgets/booking_calendar.dart
  lib/salon/presentaion/widgets/booking_execution_modal.dart
  lib/salon/presentaion/widgets/time_slots_grid.dart
  lib/shared/service/device_info.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat, ♻️ Refactor

#130 Feat: ASページAPI接続2
  lib/as(admin)/presentation/widgets/service_requester.dart
Labels: ✨ Feat

#131 Feat: アクセストークンの期限切れに伴うリフレッシュトークンの送信ロジックの実装
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/main.dart
  lib/salon/data/data_sources/booking_data_source.dart
  lib/salon/data/data_sources/notice_data_source.dart
  lib/shared/service/auth_service.dart
  lib/shared/service/token_decoder.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat

#132 Refactor: ログインとログアウトのロジック変更
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/logout_data_source.dart
  lib/auth/data/models/admin_service.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/main.dart
  lib/salon/data/data_sources/booking_data_source.dart
  lib/shared/service/auth_service.dart
  lib/shared/service/token_decoder.dart
  lib/shared/widgets/base_appbar.dart
  lib/shared/widgets/base_drawer.dart
Labels: ♻️ Refactor

#133 Fix: ログアウトボタン関連のBugを修正
  lib/auth/data/data_resources/logout_data_source.dart
  lib/auth/data/models/schedule.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/auth/presentation/pages/registration_details.dart
  lib/auth/presentation/viewmodels/login_viewmodel.dart
  lib/auth/presentation/widgets/auth_form_dropdown.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/main.dart
  lib/restaurant/presentaion/pages/meal_qr.dart
  lib/salon(admin)/domain/usecases/calendar_builders_weekday.dart
  lib/salon(admin)/presentation/pages/admin_salon_price_list.dart
  lib/salon(admin)/presentation/widgets/service_tabbar.dart
  lib/salon/presentaion/pages/admin/admin_salon_booking.dart
  lib/salon/presentaion/pages/admin/admin_salon_main.dart
  lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
  lib/salon/presentaion/pages/salon_price_list.dart
  lib/salon/presentaion/widgets/admin/booking_box.dart
  lib/salon/presentaion/widgets/admin/booking_calendar.dart
  lib/salon/presentaion/widgets/admin/edit_service_modal.dart
  lib/salon/presentaion/widgets/admin/empty_bookings.dart
  lib/salon/presentaion/widgets/admin/main_rounded_box.dart
  lib/salon/presentaion/widgets/admin/main_rounded_box_s.dart
  lib/salon/presentaion/widgets/booking_service_button.dart
  lib/salon/presentaion/widgets/filter_service_list.dart
  lib/shared/widgets/base_appbar.dart
Labels: 🚚 Rename, 🐛 Fix

#134 Fix: Null check operator used on a null value エラー修正
  lib/main.dart
  lib/shared/service/token_decoder.dart
Labels: 🐛 Fix

#137 Feat: 管理者の美容室サービスの更新、削除API通信ロジックの実装
  lib/main.dart
  lib/salon/data/data_sources/admin/admin_service_data_source.dart
  lib/salon/domain/entities/service.dart
  lib/salon/domain/usecases/admin_service_usecase.dart
  lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
  lib/salon/presentaion/widgets/admin/edit_service_button.dart
  lib/salon/presentaion/widgets/admin/edit_service_modal.dart
Labels: ✨ Feat, 💄 Design

#147 Feat: 美容室の価格表サービスを追加するAPI通信ロジックの実装
  lib/auth/data/data_resources/login_data_source.dart
  lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
  lib/salon/presentaion/viewmodels/unique_key_viewmodel.dart
  lib/salon/presentaion/widgets/admin/add_service_modal.dart
  lib/salon/presentaion/widgets/admin/category_dropdown.dart
  lib/salon/presentaion/widgets/admin/edit_service_button.dart
Labels: 🐛 Fix, ✨ Feat, ♻️ Refactor

#148 Feat: 会議室予約ページAPI連携
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/meeting_room.dart
  lib/administration/presentaion/pages/meeting_room_app.dart
  lib/administration/presentaion/pages/meeting_room_main.dart
  lib/administration/presentaion/widgets/meeting_room_card.dart
  lib/administration/presentaion/widgets/meeting_room_time.dart
  lib/main.dart
  lib/shared/widgets/meeting_room_card.dart
Labels: ✨ Feat

#150 Fix: ASページエラーの修正
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/shared/widgets/as_card.dart
Labels: 🐛 Fix

#151 Feat: 美容室管理者カテゴリー関連API通信ロジックの作成
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/salon/data/data_sources/admin/admin_category_data_source.dart
  lib/salon/domain/entities/category.dart
  lib/salon/domain/usecases/admin_category_usecase.dart
  lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
  lib/salon/presentaion/pages/salon_booking_step_one.dart
  lib/salon/presentaion/pages/salon_price_list.dart
  lib/salon/presentaion/widgets/admin/add_category_modal.dart
  lib/salon/presentaion/widgets/admin/edit_category_modal.dart
  lib/salon/presentaion/widgets/filter_group_botton.dart
Labels: 🔨 Chore, ✨ Feat, 💄 Design

#152 Feat: 食事表ページAPI連携
  lib/restaurant/presentaion/pages/menu_list.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: ✨ Feat

#153 Fix: 行政メインページ会議室予約カードエラー訂正
  lib/administration/presentaion/pages/admin_main.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: 🐛 Fix

#154 Fix: imagePicker IOS環境エラーの修正
  ios/Runner/Info.plist
Labels: 🐛 Fix

#155 Refactor: Navigatorの接続
  lib/shared/widgets/base_drawer.dart
  lib/shared/widgets/bottom_navigation_bar.dart
Labels: ♻️ Refactor

#156 Refactor: QRボタンのNavigatorの接続
  lib/dashboard/presentaion/widgets/rounded_box.dart
Labels: ♻️ Refactor

#158 Feat: 美容室予約管理ページに関するAPI通信ロジックの実装
  lib/salon/data/data_sources/admin/admin_reservation_data_source.dart
  lib/salon/data/data_sources/booking_data_source.dart
  lib/salon/data/models/admin_booking.dart
  lib/salon/domain/entities/admin_reservation.dart
  lib/salon/domain/usecases/admin_reservation_usecase.dart
  lib/salon/domain/usecases/reservation_usecase.dart
  lib/salon/presentaion/pages/admin/admin_salon_booking.dart
  lib/salon/presentaion/pages/salon_booking_step_one.dart
  lib/salon/presentaion/viewmodels/admin_reservation_viewmodel.dart
  lib/salon/presentaion/widgets/admin/admin_booking_calendar.dart
  lib/salon/presentaion/widgets/admin/booking_box.dart
  lib/salon/presentaion/widgets/admin/booking_calendar.dart
  lib/salon/presentaion/widgets/admin/empty_bookings.dart
  lib/salon/presentaion/widgets/admin/reservation_info_list.dart
  lib/salon/presentaion/widgets/admin/show_booking_state_modal.dart
  lib/salon/presentaion/widgets/booking_calendar.dart
Labels: 🔥 Remove, ✨ Feat, ♻️ Refactor

#159 Refactor: 行政ページデザインの修正
  lib/administration/presentaion/pages/as_page.dart
  lib/administration/presentaion/pages/meeting_room_main.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/widgets/sleepover_widget.dart
Labels: ♻️ Refactor

#160 Feat: バスページ関連API通信ロジックの作成
  lib/bus/data/data_sources/bus_data_source.dart
  lib/bus/data/data_sources/bus_notice_data_source.dart
  lib/bus/data/models/bus.dart
  lib/bus/domain/usecases/bus_usecase.dart
  lib/bus/presentaion/pages/bus_main.dart
  lib/bus/presentaion/pages/bus_schedule.dart
  lib/bus/presentaion/viewmodels/bus_viewmodel.dart
  lib/bus/presentaion/viewmodels/notice_viewmodel.dart
  lib/bus/presentaion/widgets/bus_dropdown_button.dart
  lib/bus/presentaion/widgets/bus_group_button.dart
  lib/bus/presentaion/widgets/bus_schedule_card.dart
  lib/bus/presentaion/widgets/bus_tabbar.dart
  lib/bus/presentaion/widgets/bus_timeline_show_modal.dart
  lib/bus/presentaion/widgets/bus_timetable.dart
  lib/salon/presentaion/widgets/admin/show_booking_state_modal.dart
  lib/salon/presentaion/widgets/filter_group_botton.dart
  lib/shared/widgets/notice_box.dart
Labels: 🔥 Remove, ✨ Feat, ♻️ Refactor

#162 Refactor: デザイン修正
  lib/administration/presentaion/pages/as_application.dart
  lib/administration/presentaion/pages/meeting_room_app.dart
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/as(admin)/presentation/pages/as_detail.dart
Labels: ♻️ Refactor

#163 Feat: 申請履歴のフィルタリング
  lib/administration/presentaion/pages/as_page.dart
Labels: ✨ Feat

#164 Feat: 学期飲料水申請API接続
  lib/restaurant/presentaion/pages/meal_application.dart
Labels: ✨ Feat

#165 Design: 設定ページUI実装
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/domain/entities/user.dart
  lib/auth/domain/usecases/update_usecase.dart
  lib/auth/presentation/pages/update_user.dart
  lib/auth/presentation/viewmodels/user_viewmodel.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/main.dart
  lib/setting/setting_page.dart
  lib/shared/widgets/bottom_navigation_bar.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat, 💄 Design, ♻️ Refactor

#166 Fix: ドロワーの追加
  lib/administration/presentaion/pages/meeting_room_app.dart
Labels: 🐛 Fix

#167 Fix: アスペクト比エラーを修正
  lib/restaurant/presentaion/pages/menu_list.dart
Labels: 🐛 Fix

#169 Fix: メインページおよびDrawerに学生情報のローディング処理
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/as_application.dart
  lib/administration/presentaion/pages/as_page.dart
  lib/administration/presentaion/pages/meeting_room_main.dart
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/auth/presentation/viewmodels/privilege_viewmodel.dart
  lib/auth/presentation/viewmodels/user_viewmodel.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/bus/presentaion/pages/bus_main.dart
  lib/bus/presentaion/pages/bus_qr.dart
  lib/bus/presentaion/pages/bus_schedule.dart
  lib/dashboard/presentaion/pages/dashboard_main.dart
  lib/dashboard/presentaion/widgets/rounded_box.dart
  lib/main.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/meal_qr.dart
  lib/restaurant/presentaion/pages/menu_list.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
  lib/salon/presentaion/pages/admin/admin_salon_price_list.dart
  lib/salon/presentaion/pages/salon_booking_step_one.dart
  lib/salon/presentaion/pages/salon_booking_step_two.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/salon/presentaion/pages/salon_my_book.dart
  lib/salon/presentaion/pages/salon_price_list.dart
  lib/shared/widgets/base_appbar.dart
  lib/shared/widgets/base_drawer.dart
Labels: 🐛 Fix, ♻️ Refactor

#170 Refactor: Googleログインロジック整理
  ios/.gitignore
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/shared/widgets/base_appbar.dart
Labels: 🔨 Chore, ♻️ Refactor

#171 Fix: ドロワーの欠落修正
  lib/salon/presentaion/pages/salon_booking_step_one.dart
  lib/salon/presentaion/pages/salon_booking_step_two.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/salon/presentaion/pages/salon_my_book.dart
  lib/salon/presentaion/pages/salon_price_list.dart
Labels: 🐛 Fix

#173 Refactor: デザイン修正
  lib/administration/presentaion/pages/as_application.dart
  lib/administration/presentaion/pages/meeting_room_app.dart
Labels: ♻️ Refactor

#174 Refactor: コメントロジックの分離に伴う関連ファイルのリファクタリング
  lib/as(admin)/data/data_sources/as_comment_data_source.dart
  lib/as(admin)/data/models/as_comment.dart
  lib/as(admin)/data/models/as_list.dart
  lib/as(admin)/domain/entities/comment.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/as(admin)/presentation/viewmodels/as_viewmodel.dart
  lib/as(admin)/presentation/viewmodels/comment_viewmodel.dart
  lib/as(admin)/presentation/widgets/admin_as_floating_button.dart
  lib/as(admin)/presentation/widgets/as_updating_comment_modal.dart
  lib/as(admin)/presentation/widgets/as_writing_comment_modal.dart
  lib/shared/widgets/as_comment_box.dart
Labels: 🐛 Fix, ♻️ Refactor

#176 Feat: ASページ電話発信機能の実装
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner/Info.plist
  lib/as(admin)/presentation/widgets/service_requester.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 🔨 Chore, ✨ Feat

#180 Refactor: API接続と曜日別ボタンを有効にする
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: ♻️ Refactor

#181 Refactor: 学期飲料口座番号API接続
  lib/restaurant/presentaion/pages/meal_application.dart
Labels: ♻️ Refactor

#182 Feat: API接続
  lib/restaurant/presentaion/pages/weekend_meal.dart
Labels: ✨ Feat

#185 Feat: 最近1件のお知らせウィジェットの実装
  ios/Runner.xcodeproj/project.pbxproj
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/data/data_resources/reset_password_data_source.dart
  lib/auth/domain/entities/user.dart
  lib/auth/domain/entities/verify.dart
  lib/auth/domain/usecases/detail_usecase.dart
  lib/auth/domain/usecases/reset_password_usecase.dart
  lib/auth/domain/usecases/reset_password_verify_code_usecase.dart
  lib/auth/presentation/pages/mail_verification_code.dart
  lib/auth/presentation/pages/registration_details.dart
  lib/auth/presentation/pages/reset_password.dart
  lib/auth/presentation/pages/student_login.dart
  lib/auth/presentation/viewmodels/verify_code_viewmodel.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/auth/presentation/widgets/international_admin_login_form.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/dashboard/data/data_sources/urgent_data_source.dart
  lib/dashboard/data/models/urgent.dart
  lib/dashboard/presentaion/pages/dashboard_main.dart
  lib/dashboard/presentaion/viewmodels/urgent_viewmodel.dart
  lib/dashboard/presentaion/widgets/rounded_box.dart
  lib/main.dart
  lib/routes/app_routes.dart
  lib/setting/setting_page.dart
  lib/shared/service/auth_service.dart
  lib/shared/service/interceptor.dart
  lib/shared/service/logout_service.dart
  lib/shared/widgets/base_appbar.dart
  lib/shared/widgets/base_drawer.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, 🚚 Rename, ✨ Feat, ♻️ Refactor

#186 Fix: APIの修正によるエラーの修正
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
Labels: 🐛 Fix

#187 Feat: Userモデルの修正
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/models/admin_service.dart
  lib/auth/data/models/schedule.dart
  lib/auth/data/models/user.dart
  lib/auth/data/models/user_service.dart
  lib/auth/presentation/pages/update_user.dart
  lib/auth/presentation/viewmodels/privilege_viewmodel.dart
  lib/dashboard/data/data_sources/urgent_data_source.dart
Labels: 🔥 Remove, ♻️ Refactor

#188 Refactor: 外出/外泊重複可能修正
  lib/administration/presentaion/pages/meeting_room_app.dart
Labels: ♻️ Refactor

#189 Refactor: 外出/外泊重複可能修正
  lib/administration/presentaion/pages/sleepover_application.dart
Labels: ♻️ Refactor

#198 Feat: インターセプターのコンストラクター追加及び_retryメソッドに再試行ロジック追加
  lib/as(admin)/data/data_sources/as_comment_data_source.dart
  lib/as(admin)/domain/usecases/as_comment_usecase.dart
  lib/as(admin)/presentation/viewmodels/comment_viewmodel.dart
  lib/bus/data/data_sources/bus_data_source.dart
  lib/bus/data/data_sources/bus_notice_data_source.dart
  lib/bus/domain/usecases/bus_usecase.dart
  lib/salon/data/data_sources/notice_data_source.dart
  lib/salon/data/data_sources/price_data_source.dart
  lib/salon/data/models/notice.dart
  lib/salon/presentaion/viewmodels/category_viewmodel.dart
  lib/salon/presentaion/viewmodels/service_viewmodel.dart
  lib/shared/service/interceptor.dart
Labels: ✨ Feat, ♻️ Refactor

#199 Feat: トークンの有無に応じた処理、ヘッダー設定ロジックの追加
  lib/as(admin)/data/data_sources/as_data_source.dart
  lib/as(admin)/data/data_sources/as_status_data_source.dart
  lib/as(admin)/data/models/as_comment.dart
  lib/as(admin)/domain/usecases/as_status_usecase.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/as(admin)/presentation/viewmodels/as_viewmodel.dart
  lib/as(admin)/presentation/viewmodels/comment_viewmodel.dart
  lib/auth/presentation/viewmodels/privilege_viewmodel.dart
  lib/main.dart
  lib/shared/service/auth_service.dart
  lib/shared/service/interceptor.dart
  lib/shared/widgets/as_comment_box.dart
  lib/shared/widgets/base_appbar.dart
Labels: 🔨 Chore, 🐛 Fix, ✨ Feat, ♻️ Refactor
