Repository Shining-Jicheon-Stars/yjg-dart-flutter-frontend, pull requests merged in 2024-04, with the labels that each got.

#200 Feat: 飲料水申請期間のみボタンクリック可能機能
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: ✨ Feat

#201 Develop
  lib/as(admin)/data/data_sources/as_status_data_source.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/auth/presentation/pages/update_user.dart
  lib/main.dart
  lib/salon/data/data_sources/admin/admin_category_data_source.dart
  lib/salon/data/data_sources/admin/admin_reservation_data_source.dart
  lib/salon/data/data_sources/my_booking_data_source.dart
  lib/salon/data/data_sources/notice_data_source.dart
  lib/salon/data/models/notice.dart
  lib/salon/domain/usecases/admin_category_usecase.dart
  lib/salon/domain/usecases/admin_reservation_usecase.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/salon/presentaion/pages/salon_price_list.dart
  lib/salon/presentaion/widgets/admin/edit_category_modal.dart
  lib/salon/presentaion/widgets/admin/edit_service_modal.dart
  lib/salon/presentaion/widgets/my_booking_list.dart
  lib/shared/widgets/as_comment_box.dart
Labels: 🔨 Chore, 🔥 Remove, 🐛 Fix, ✨ Feat, ♻️ Refactor

#202 Develop
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: 🐛 Fix

#203 Feat: パスワードリセットロジックの実装
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/data/data_resources/reset_password_data_source.dart
  lib/auth/data/data_resources/user_data_source.dart
  lib/auth/domain/entities/user.dart
  lib/auth/domain/usecases/detail_usecase.dart
  lib/auth/domain/usecases/reset_password_new_usecase.dart
  lib/auth/domain/usecases/reset_password_verify_code_usecase.dart
  lib/auth/domain/usecases/update_usecase.dart
  lib/auth/presentation/pages/new_password_update.dart
  lib/auth/presentation/widgets/international_admin_login_form.dart
  lib/dashboard/data/data_sources/urgent_data_source.dart
  lib/dashboard/presentaion/viewmodels/urgent_viewmodel.dart
  lib/routes/app_routes.dart
  lib/shared/service/interceptor.dart
Labels: ✨ Feat, ♻️ Refactor

#204 Refactor: 美容室ページのAPIロジックにDioインターセプターを適用
  lib/salon/data/data_sources/admin/admin_service_data_source.dart
  lib/salon/data/data_sources/booking_data_source.dart
  lib/salon/data/data_sources/my_booking_data_source.dart
  lib/salon/data/data_sources/price_data_source.dart
  lib/salon/domain/usecases/admin_service_usecase.dart
  lib/salon/presentaion/viewmodels/booking_business_hours_viewmodel.dart
  lib/salon/presentaion/viewmodels/reservations_viewmodel.dart
Labels: ♻️ Refactor

#205 Feat: お知らせ詳細ビューページの作成、デザインの変更
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/notice_detail_page.dart
Labels: ✨ Feat

#206 Refactor: 飲料水ボタン2個のローディングデザインを修正
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: ♻️ Refactor

#207 Refactor: 飲料水申請デザイン機能の修正
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
Labels: ♻️ Refactor

#208 Refactor: Auth関連APIロジックにDioインターセプターを適用
  lib/administration/presentaion/pages/admin_main.dart
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/logout_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/data/data_resources/reset_password_data_source.dart
  lib/auth/data/data_resources/user_data_source.dart
  lib/auth/domain/usecases/detail_usecase.dart
  lib/auth/domain/usecases/update_usecase.dart
  lib/auth/presentation/widgets/international_admin_login_form.dart
  lib/bus/domain/usecases/bus_usecase.dart
  lib/dashboard/data/data_sources/urgent_data_source.dart
Labels: 🔥 Remove, ♻️ Refactor

#209 Fix: Googleログインの追加情報入力のロジックを修正
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/user_data_source.dart
  lib/auth/presentation/pages/registration_details.dart
  lib/auth/presentation/viewmodels/user_viewmodel.dart
  lib/auth/presentation/widgets/google_login_button.dart
Labels: 🐛 Fix

#210 Fix: 個人情報の修正に関するロジックの修正
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/user_data_source.dart
  lib/auth/presentation/pages/update_user.dart
Labels: 🐛 Fix

#212 Fix: リフレッシュトークンのJSON返却キー値の修正
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/reset_password_data_source.dart
  lib/salon/presentaion/viewmodels/category_viewmodel.dart
Labels: 🐛 Fix

#213 Refactor: BottomNavigationBarのHomeボタン修正
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/auth/data/data_resources/logout_data_source.dart
  lib/shared/widgets/bottom_navigation_bar.dart
Labels: 💄 Design, ♻️ Refactor

#214 Refactor: レストランページAPI全体のデータソース分離およびDioインターセプターの適用
  lib/restaurant/data/data_sources/meal_reservation_data_source.dart
  lib/restaurant/data/data_sources/menu_data_source.dart
  lib/restaurant/data/data_sources/semester_meal_reservation_data_source.dart
  lib/restaurant/data/data_sources/weekend_meal_reservation_data_source.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/meal_qr.dart
  lib/restaurant/presentaion/pages/menu_list.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
Labels: ♻️ Refactor

#217 Refactor: 会議室のページデザインを編集
  lib/administration/presentaion/pages/meeting_room_app.dart
  lib/administration/presentaion/pages/meeting_room_main.dart
Labels: ♻️ Refactor

#218 Refactor: 外泊/外出申請キャンセルAPIロジックファイルの分離およびdioインターセプターの適用
  lib/administration/data/data_sources/sleepover_data_source.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/widgets/sleepover_widget.dart
  lib/administration/presentaion/widgets/std_as_floating_button.dart
Labels: 🐛 Fix, 💄 Design, ♻️ Refactor

#219 Fix: メール重複チェックAPIエンドポイントの修正
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/presentation/pages/international_registration.dart
Labels: 🐛 Fix

#220 Fix: 自動ログインbug修正
  lib/main.dart
  lib/routes/app_routes.dart
  lib/shared/service/auth_service.dart
  lib/shared/service/token_decoder.dart
Labels: 🔥 Remove, 🐛 Fix

#221 Feat: トークン中央管理シングルトンクラスの実装
  lib/auth/data/data_resources/login_data_source.dart
  lib/main.dart
  lib/shared/service/interceptor.dart
  lib/shared/service/token_refresh_manager.dart
Labels: ✨ Feat, ♻️ Refactor

#222 Fix: Android環境のGoogleログイン一部修正
  android/.gitignore
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/salon/presentaion/viewmodels/service_viewmodel.dart
  lib/shared/service/token_refresh_manager.dart
Labels: 🐛 Fix

#223 Refactor: APIの変更によるコードの修正
  lib/restaurant/data/data_sources/meal_reservation_data_source.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
Labels: ♻️ Refactor

#224 Feat: お知らせ詳細ページのルーターを分離及びお知らせウィジェットと接続
  lib/administration/data/data_sources/notice_data_source.dart
  lib/administration/presentaion/pages/notice.dart
  lib/administration/presentaion/pages/notice_detail_page.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/bus/presentaion/pages/bus_main.dart
  lib/routes/app_routes.dart
  lib/salon/presentaion/pages/admin/admin_salon_main.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/shared/service/navigate_and_remove_until.dart
Labels: 🐛 Fix, ✨ Feat

#225 Fix: 自動ログイン処理の条件修正
  lib/shared/service/auth_service.dart
Labels: 🐛 Fix

#226 Feat: 確認モーダルを追加
  lib/as(admin)/presentation/widgets/admin_as_floating_button.dart
  lib/auth/data/data_resources/logout_data_source.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/salon/presentaion/widgets/admin/show_booking_state_modal.dart
  lib/salon/presentaion/widgets/my_booking_modal.dart
Labels: ✨ Feat, ♻️ Refactor

#228 Refactor: デザイン修正
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/widgets/std_as_floating_button.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
Labels: ♻️ Refactor

#229 Feat: アプリ署名の追加
  android/app/build.gradle
Labels: ✨ Feat

#231 Fix: 美容室のカテゴリのデフォルト値をリセットするロジックを修正
  android/app/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/domain/usecases/register_usecase.dart
  lib/main.dart
  lib/salon/presentaion/viewmodels/user_selection_viewmodel.dart
  lib/salon/presentaion/widgets/filter_group_botton.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔥 Remove, 🐛 Fix, ✨ Feat, ♻️ Refactor

#232 Chore: Googleログインの自動ログイン処理
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/main.dart
  lib/shared/service/auth_service.dart
Labels: 🔨 Chore

#233 Refactor: aabを取得するための設定
  .gitignore
  android/app/build.gradle
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
  pubspec.lock
Labels: ♻️ Refactor

#234 Fix: initRoute関連ロジックの修正
  lib/shared/service/auth_service.dart
Labels: 🐛 Fix

#235 Refactor: asページエラーを修正
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/as_application.dart
  lib/administration/presentaion/pages/as_page.dart
Labels: ♻️ Refactor

#236 Refactor: 状態管理ロジックの改善
  lib/bus/presentaion/pages/bus_schedule.dart
  lib/dashboard/presentaion/pages/dashboard_main.dart
  lib/salon/presentaion/viewmodels/reservations_viewmodel.dart
  lib/salon/presentaion/widgets/my_booking_list.dart
  pubspec.lock
Labels: 🐛 Fix, ♻️ Refactor

#237 Fix: 例外処理の漏れを修正
  lib/shared/service/auth_service.dart
Labels: 🐛 Fix

#238 Fix: ナビゲーターのエラー修正
  lib/salon/domain/usecases/reservation_usecase.dart
Labels: 🐛 Fix

#239 Feat: データ更新機能を追加
  lib/as(admin)/presentation/pages/admin_as_main.dart
  lib/salon/presentaion/widgets/admin/admin_booking_calendar.dart
  lib/salon/presentaion/widgets/my_booking_list.dart
  lib/shared/widgets/mini_rounded_box.dart
Labels: 🐛 Fix, ✨ Feat

#241 Refactor: アプリ配布エラーを修正
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/profile/AndroidManifest.xml
  lib/administration/data/data_sources/std_as_data_source.dart
  lib/administration/presentaion/pages/as_application.dart
  pubspec.lock
  pubspec.yaml
Labels: ♻️ Refactor
