Repository Shining-Jicheon-Stars/yjg-dart-flutter-frontend, pull requests merged in 2024-02, with the labels that each got.

#28 Fix :項目を選択しなかったときのエラーの修正
  lib/screens/restaurant/meal_application.dart
  lib/screens/restaurant/meal_qr.dart
  lib/screens/restaurant/weekend_meal.dart
Labels: 🐛 Fix

#30 Feat: 行政メインページの追加
  lib/main.dart
  lib/screens/admin/admin_main.dart
  lib/screens/restaurant/restaurant_main.dart
Labels: ✨ Feat

#38 Design: バスの時刻表UIの実装
  analysis_options.yaml
  lib/main.dart
  lib/screens/bus/bus_dropdown_button.dart
  lib/screens/bus/bus_qr.dart
  lib/screens/bus/bus_schedule.dart
  lib/screens/bus/bus_timeline.dart
  lib/screens/bus/bus_timetable.dart
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat, 💄 Design

#39 Feat: お知らせ ページ
  lib/main.dart
  lib/screens/admin/admin_main.dart
  lib/screens/admin/notice.dart
  lib/screens/restaurant/restaurant_main.dart
  lib/widgets/move_button.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feat

#40 Design: 美容室予約UI実装
  lib/salon/presentaion/pages/salon_booking.dart
  lib/salon/presentaion/widgets/booking_calendar.dart
  lib/salon/presentaion/widgets/booking_next_button.dart
  lib/salon/presentaion/widgets/booking_service_select.dart
Labels: 💄 Design

#44 Chore: インポートパスの修正
  lib/salon/presentaion/pages/salon_price_list.dart
Labels: 🔨 Chore

#45 Design: バス時刻表ページUI改善
  lib/bus/presentaion/pages/bus_schedule.dart
  lib/bus/presentaion/pages/bus_schedule_test.dart
  lib/bus/presentaion/widgets/bus_tabbar.dart
  lib/bus/presentaion/widgets/bus_timeline_show_modal.dart
  lib/bus/presentaion/widgets/bus_timetable.dart
Labels: 💄 Design

#46 Feat: 外泊申請ページ
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/administration/presentaion/widget/sleepover_widget.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feat

#48 Feat: CODEOWNERS生成
  .github/CODEOWNERS
Labels: ✨ Feat

#49 Chore: イメージ追加
  assets/img/google_logo.png
  assets/img/yju_text_logo.png
Labels: 🔨 Chore

#50 Design: AuthページのUI実装
  lib/administration/presentaion/pages/sleepover.dart
  lib/administration/presentaion/widgets/sleepover_widget.dart
  lib/auth/domain/usecases/BirthDateInputFormatter.dart
  lib/auth/domain/usecases/PhoneNumberInpurtFormatter.dart
  lib/auth/presentation/pages/international_registration_step1.dart
  lib/auth/presentation/pages/international_registration_step2.dart
  lib/auth/presentation/pages/login_google_domestic_students.dart
  lib/auth/presentation/pages/login_standard_foreign_international.dart
  lib/auth/presentation/pages/registration_details.dart
  lib/auth/presentation/widgets/auth_form_dropdown.dart
  lib/auth/presentation/widgets/auth_text_button.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/auth/presentation/widgets/international_admin_login_form.dart
  lib/bus/presentaion/widgets/bus_timeline_show_modal.dart
  lib/bus/presentaion/widgets/bus_timetable.dart
  lib/main.dart
Labels: 🔨 Chore, ✨ Feat, 💄 Design

#52 Fix: キーボード表示時のオーバーフロー発生によりSingleChildScrollViewウィジェット追加
  lib/auth/presentation/pages/international_registration_step1.dart
  lib/auth/presentation/pages/international_registration_step2.dart
  lib/auth/presentation/pages/login_google_domestic_students.dart
  lib/auth/presentation/pages/login_standard_foreign_international.dart
Labels: 🐛 Fix

#53 Feat: 会議室ページ
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/meeting_room.dart
  lib/administration/presentaion/widget/meeting_room_card.dart
  lib/administration/presentaion/widget/meeting_room_time.dart
  lib/main.dart
Labels: ✨ Feat

#55 Chore: CODEOWNERSを修正
  .github/CODEOWNERS
  .github/auto_assign.yml
  .github/workflows/pr_assignee.yml
Labels: 🔨 Chore

#56 Fix: 機種によるオーバーフロー発生でPadding値の調整
  lib/auth/presentation/pages/login_google_domestic_students.dart
  lib/auth/presentation/pages/login_standard_foreign_international.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/google_login_button.dart
Labels: 🔨 Chore, 🐛 Fix, ✨ Feat

#63 Design: 美容室(管理者)メインページUI実装
  lib/salon(admin)/presentation/pages/admin_salon_main.dart
  lib/salon(admin)/presentation/widgets/main_rounded_box.dart
  lib/salon(admin)/presentation/widgets/main_rounded_box_s.dart
Labels: 💄 Design

#64 Feat: トップスクロールを防ぐためのCustomSingleChildScrollViewウィジェットの実装
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/meeting_room.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
  lib/salon(admin)/domain/usecases/calendar_builders_weekday.dart
  lib/salon(admin)/presentation/pages/admin_salon_main.dart
  lib/shared/widgets/CustomSingleChildScrollView.dart
Labels: ✨ Feat

#65 Design: 予約管理ページのUI実装
  lib/salon(admin)/presentation/pages/admin_salon_booking.dart
  lib/salon(admin)/presentation/pages/admin_salon_main.dart
  lib/salon(admin)/presentation/widgets/booking_box.dart
  lib/salon(admin)/presentation/widgets/booking_calendar.dart
  lib/salon/presentaion/pages/salon_booking.dart
Labels: 💄 Design

#66 Design: 美容院の価格表ページのUI実装(管理者向け)
  lib/salon(admin)/presentation/pages/admin_salon_main.dart
  lib/salon(admin)/presentation/pages/admin_salon_price_list.dart
  lib/salon(admin)/presentation/widgets/booking_box.dart
  lib/salon(admin)/presentation/widgets/edit_service_modal.dart
  lib/salon(admin)/presentation/widgets/service_tabbar.dart
Labels: 🔨 Chore, 💄 Design

#70 Design: 予約履歴がない場合Emptyウィジェットを見せる
  .gitignore
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/auth/domain/entities/user.dart
  lib/auth/presentation/pages/international_registration.dart
  lib/auth/presentation/pages/international_registration_step1.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/international_admin_login_form.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/salon(admin)/presentation/widgets/booking_calendar.dart
  lib/salon(admin)/presentation/widgets/empty_bookings.dart
  lib/shared/constants/api_url.dart
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Podfile
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat, 💄 Design, ♻️ Refactor

#71 Fix: ディレクトリ構造の変更
  lib/administration/presentaion/widgets/meeting_room_time.dart
Labels: 🐛 Fix

#72 Feat：ログイン(語学堂学生向け)実装
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/domain/usecases/BirthDateInputFormatter.dart
  lib/auth/domain/usecases/PhoneNumberInpurtFormatter.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/auth/presentation/pages/international_registration.dart
  lib/auth/presentation/viewmodels/user_viewmodel.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/auth/presentation/widgets/login_button.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, 🚚 Rename, 🔥 Remove, ✨ Feat

#73 Feat: 会員登録ページ(語学堂学生用)API通信ロジックの実装
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/domain/usecases/register_usecase.dart
  lib/auth/presentation/pages/international_registration.dart
Labels: ✨ Feat

#74 Feat: QRコード一時追加
  lib/administration/presentaion/pages/meeting_room.dart
  lib/restaurant/presentaion/pages/meal_qr.dart
Labels: ✨ Feat

#76 Feat: Googleログインのロジック作成
  android/.gitignore
  android/app/build.gradle
  android/build.gradle
  ios/.gitignore
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
  lib/administration/presentaion/pages/admin_main.dart
  lib/administration/presentaion/pages/meeting_room.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/presentation/pages/international_registration.dart
  lib/auth/presentation/viewmodels/email_viewmodel.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/restaurant_main.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
  lib/salon(admin)/presentation/pages/admin_salon_main.dart
  lib/shared/widgets/custom_singlechildscrollview.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  web/index.html
Labels: 🔨 Chore, ✨ Feat

#80 Design: 管理者用のASページUI実装
  assets/fonts/Pretendard-Black.ttf
  assets/fonts/Pretendard-ExtraBold.ttf
  assets/fonts/Pretendard-ExtraLight.ttf
  assets/fonts/Pretendard-Light.ttf
  assets/fonts/Pretendard-Medium.ttf
  assets/fonts/Pretendard-Thin.ttf
  lib/administration/presentaion/pages/as_page.dart
  lib/administration/presentaion/widgets/as_card.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/as(admin)/presentation/pages/as_main.dart
  lib/as(admin)/presentation/widgets/as_floating_button.dart
  lib/as(admin)/presentation/widgets/as_notice_box.dart
  lib/as(admin)/presentation/widgets/as_tabbar.dart
  lib/as(admin)/presentation/widgets/as_writing_comment_modal.dart
  lib/as(admin)/presentation/widgets/service_requester.dart
  lib/main.dart
  lib/shared/theme/palette.dart
  lib/shared/widgets/as_card.dart
  lib/shared/widgets/as_comment_box.dart
  lib/shared/widgets/as_image_view.dart
  lib/shared/widgets/as_image_view_detail.dart
  lib/shared/widgets/base_appbar.dart
  lib/shared/widgets/move_button.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat, 💄 Design

#81 Feat: 学期飲料水申請API 1次連動
  lib/auth/presentation/pages/registration_details.dart
  lib/main.dart
  lib/restaurant/presentaion/pages/meal_application.dart
Labels: ✨ Feat

#85 Feat: ログアウトロジック追加
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/presentation/widgets/google_login_button.dart
  lib/shared/widgets/base_drawer.dart
Labels: 🔨 Chore, 🚚 Rename, ✨ Feat

#87 Refactor: コードフォーマット
  lib/restaurant/presentaion/pages/weekend_meal.dart
  lib/salon(admin)/presentation/widgets/booking_box.dart
  lib/salon(admin)/presentation/widgets/edit_service_modal.dart
  lib/salon(admin)/presentation/widgets/service_tabbar.dart
  lib/salon/data/models/Price.dart
  lib/salon/presentaion/pages/salon_main.dart
  lib/salon/presentaion/widgets/service_tabbar.dart
  lib/shared/widgets/as_card.dart
  lib/shared/widgets/as_image_view.dart
  lib/shared/widgets/base_drawer.dart
  lib/shared/widgets/custom_rounded_button.dart
  lib/shared/widgets/move_button.dart
Labels: ♻️ Refactor

#89 Fix: メール重複チェックロジックの修正
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/register_data_source.dart
  lib/auth/presentation/pages/international_registration.dart
  lib/auth/presentation/viewmodels/email_viewmodel.dart
  lib/auth/presentation/widgets/auth_text_form_field.dart
  lib/salon/presentaion/pages/salon_price_list.dart
Labels: 🐛 Fix

#93 Feat: 画像ビュースワイプ機能追加
  lib/shared/widgets/as_image_view.dart
  lib/shared/widgets/as_image_view_detail.dart
Labels: ✨ Feat

#95 Fix: Navigator.pushNamedからpushNamedAndRemoveUntilに変更（ログイン後に戻るを防止）
  lib/as(admin)/presentation/widgets/as_floating_button.dart
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/domain/entities/user.dart
  lib/auth/domain/usecases/detail_usecase.dart
  lib/auth/domain/usecases/login_usecase.dart
  lib/auth/domain/usecases/register_usecase.dart
Labels: 🐛 Fix

#96 Fix: submitMealApplicationのbody修正
  lib/restaurant/presentaion/pages/meal_application.dart
Labels: 🐛 Fix
