Repository Shining-Jicheon-Stars/yjg-dart-flutter-frontend, pull requests merged in 2024-05, with the labels that each got.

#242 Chore: Firebase（FCM）の環境構築
  .gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/settings.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcworkspace/contents.xcworkspacedata
  ios/Runner/Info.plist
  ios/Runner/Runner.entitlements
  lib/firebase_api.dart
  lib/main.dart
  macos/.gitignore
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Runner.xcodeproj/project.pbxproj
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: 🔨 Chore

#244 Feat: プッシュ通知の実装
  android/app/src/main/res/mipmap/ic_launcher.png
  lib/administration/presentaion/pages/as_page.dart
  lib/auth/data/data_resources/logout_data_source.dart
  lib/firebase_api.dart
  lib/main.dart
  lib/shared/service/notification_service.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, 🔥 Remove, ✨ Feat

#246 Feat: ログイン時にFCMトークンをサーバーに送信するロジックを追加
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/logout_data_source.dart
  lib/firebase_api.dart
  lib/main.dart
  lib/routes/app_routes.dart
  lib/setting/data/data_sources/fcm_token_datasource.dart
  lib/setting/presentation/pages/setting_page.dart
  lib/shared/service/auth_service.dart
Labels: 🚚 Rename, ✨ Feat

#247 Feat: プッシュ通知のオン/オフ機能の実装
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/data_resources/user_data_source.dart
  lib/auth/domain/usecases/detail_usecase.dart
  lib/auth/domain/usecases/update_usecase.dart
  lib/auth/presentation/pages/update_user.dart
  lib/setting/data/data_sources/fcm_token_datasource.dart
  lib/setting/domain/entities/push.dart
  lib/setting/domain/usecases/push_notification_usecase.dart
  lib/setting/presentation/pages/setting_page.dart
  lib/shared/service/snack_bar.dart
Labels: 🔥 Remove, 🐛 Fix, ✨ Feat

#248 Feat: ホームウィジェットによるレストランQRページ移動の実装
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/yeungjin/global_app/MyAppWidgetProvider.java
  android/app/src/main/kotlin/com/example/yjg/MainActivity.kt
  android/app/src/main/res/drawable/res_preview.png
  android/app/src/main/res/drawable/restaurantqr.png
  android/app/src/main/res/layout/widget_layout.xml
  android/app/src/main/res/xml/widget_info.xml
  android/build.gradle
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feat

#249 Refactor: プッシュ通知（FCM）の設定一部変更
  android/app/build.gradle
  android/build.gradle
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/auth/data/models/user.dart
  lib/auth/presentation/pages/update_user.dart
  lib/firebase_api.dart
  lib/main.dart
  lib/salon/presentaion/widgets/filter_service_list.dart
  lib/setting/data/data_sources/fcm_token_datasource.dart
  lib/setting/presentation/pages/setting_page.dart
  lib/shared/service/auth_service.dart
  lib/shared/service/notification_service.dart
  lib/shared/widgets/as_card.dart
  lib/shared/widgets/base_drawer.dart
  lib/shared/widgets/bottom_navigation_bar.dart
  pubspec.lock
Labels: 🔨 Chore, 🐛 Fix, ♻️ Refactor

#250 Fix: 飲料水QRホームウィジェットのバグ修正
  android/app/build.gradle
  android/app/src/main/kotlin/com/example/yjg/MainActivity.kt
  android/build.gradle
  android/gradle.properties
  lib/main.dart
Labels: 🐛 Fix

#251 Chore: gitignore設定
  .gitignore
  android/.gitignore
Labels: 🔨 Chore

#254 Feat: QRコード画像を取得するためのAPI通信ロジック作成
  lib/auth/data/data_resources/google_login_data_source.dart
  lib/auth/data/data_resources/login_data_source.dart
  lib/bus/data/data_sources/bus_data_source.dart
  lib/bus/presentaion/pages/bus_qr.dart
  lib/restaurant/presentaion/pages/meal_qr.dart
  lib/salon/presentaion/viewmodels/booking_business_hours_viewmodel.dart
  lib/shared/datasources/qr_img_data_source.dart
  lib/shared/service/storage.dart
  lib/shared/service/user_info.dart
  lib/shared/widgets/base_drawer.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, 🚚 Rename, ✨ Feat, ♻️ Refactor

#255 Refactor: トークン値によるウィジェットページ
  android/app/build.gradle
  android/app/src/main/java/yeungjin/global_app/MyAppWidgetProvider.java
  android/app/src/main/java/yeungjin/global_app/MySecondAppWidgetProvider.java
  android/app/src/main/kotlin/com/example/yjg/MainActivity.kt
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: ♻️ Refactor

#256 Fix: メインダッシュボードのボタンナビゲーターにメディアクエリを適用
  lib/administration/data/data_sources/sleepover_data_source.dart
  lib/administration/presentaion/pages/meeting_room_main.dart
  lib/administration/presentaion/pages/sleepover_application.dart
  lib/as(admin)/data/data_sources/as_comment_data_source.dart
  lib/as(admin)/presentation/pages/as_detail.dart
  lib/dashboard/presentaion/pages/dashboard_main.dart
  lib/restaurant/presentaion/pages/meal_application.dart
  lib/restaurant/presentaion/pages/weekend_meal.dart
  lib/salon/data/data_sources/admin/admin_reservation_data_source.dart
  lib/salon/presentaion/widgets/time_slots_grid.dart
  pubspec.lock
Labels: 🐛 Fix, ♻️ Refactor
