Repository Shining-Jicheon-Stars/yjg-dart-flutter-frontend, pull requests merged in 2024-01, with the labels that each got.

#2 Docs: Add Create pull_request_template.md
  .github/pull_request_template.md
Labels: 📝 Docs

#4 Design: Designating the Default Theme for the Application
  lib/theme/app_theme.dart
  lib/theme/pallete.dart
  lib/theme/theme.dart
Labels: 💄 Design

#7 Feat : メニューリトの変更
  lib/screens/restaurant/menu_list.dart
Labels: ✨ Feat

#9 Feat: MoveButton
  lib/main.dart
  lib/screens/restaurant/menu_list.dart
  lib/screens/restaurant/restaurant_main.dart
  lib/widgets/move_button.dart
Labels: ✨ Feat

#11 Design: ナビゲーションドロワーのアイコン追加　その他２
  lib/common/mini_rounded_box.dart
  lib/screens/dashboard/dashboard_main.dart
  lib/screens/dashboard/rounded_box.dart
  lib/widgets/base_appbar.dart
Labels: 💄 Design

#12 Design: ナビゲーションドロワーUI
  lib/screens/dashboard/dashboard_main.dart
  lib/widgets/base_drawer.dart
  pubspec.lock
  pubspec.yaml
Labels: 💄 Design

#13 Design: 不透明度プロパティ(withOpacity)追加
  lib/widgets/move_button.dart
Labels: 💄 Design

#14 Feat: 週末の食事ページ
  lib/screens/restaurant/weekend_meal.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feat

#15 Feat: 週末の食事ページ
  assets/img/yju_logo.png
  assets/img/yju_tiger_logo.png
  lib/common/custom_rounded_button.dart
  lib/common/mini_rounded_box.dart
  lib/main.dart
  lib/screens/dashboard/dashboard_main.dart
  lib/screens/dashboard/rounded_box.dart
  lib/screens/restaurant/menu_list.dart
  lib/screens/restaurant/restaurant_main.dart
  lib/screens/restaurant/weekend_meal.dart
  lib/theme/app_theme.dart
  lib/theme/pallete.dart
  lib/theme/theme.dart
  lib/widgets/base_appbar.dart
  lib/widgets/base_drawer.dart
  lib/widgets/bottom_navigation_bar.dart
  lib/widgets/move_button.dart
  pubspec.lock
  pubspec.yaml
Labels: ✨ Feat

#16 Revert "Feat: 週末の食事ページ"
  assets/img/yju_logo.png
  assets/img/yju_tiger_logo.png
  lib/common/custom_rounded_button.dart
  lib/common/mini_rounded_box.dart
  lib/main.dart
  lib/screens/dashboard/dashboard_main.dart
  lib/screens/dashboard/rounded_box.dart
  lib/screens/restaurant/menu_list.dart
  lib/screens/restaurant/restaurant_main.dart
  lib/screens/restaurant/weekend_meal.dart
  lib/theme/app_theme.dart
  lib/theme/pallete.dart
  lib/theme/theme.dart
  lib/widgets/base_appbar.dart
  lib/widgets/base_drawer.dart
  lib/widgets/bottom_navigation_bar.dart
  lib/widgets/move_button.dart
  pubspec.lock
  pubspec.yaml
Labels: ⏪️ Revert

#17 Design: 美容室ページ関連のUI実装
  lib/common/blue_main_rounded_box.dart
  lib/common/notice_box.dart
  lib/common/white_main_rounded_box.dart
  lib/main.dart
  lib/screens/salon/salon_main.dart
Labels: 🔨 Chore, 💄 Design

#18 Chore: 'price_list'ルーターの追加　その他　２
  lib/main.dart
  lib/screens/dashboard/dashboard_main.dart
  lib/screens/salon/salon_main.dart
  lib/widgets/base_appbar.dart
Labels: 🔨 Chore, 💄 Design

#19 Design: 美容室の料金表ページUI実装　その他４
  assets/test.json
  lib/screens/salon/Price.dart
  lib/screens/salon/multi_select.dart
  lib/screens/salon/salon_price_list.dart
  pubspec.lock
  pubspec.yaml
Labels: 🔨 Chore, ✨ Feat, 💄 Design

#20 Feat: 食事申込ページ
  lib/main.dart
  lib/screens/restaurant/meal_application.dart
  lib/screens/restaurant/restaurant_main.dart
Labels: ✨ Feat

#21 Design: ドロワー追加
  lib/screens/restaurant/meal_application.dart
  lib/screens/restaurant/menu_list.dart
  lib/screens/restaurant/restaurant_main.dart
  lib/screens/restaurant/weekend_meal.dart
Labels: 💄 Design

#24 Chore: ファイル及びクラス名の誤字を修正(palette.dart, Palette)
  lib/common/blue_main_rounded_box.dart
  lib/common/custom_rounded_button.dart
  lib/common/mini_rounded_box.dart
  lib/common/white_main_rounded_box.dart
  lib/screens/dashboard/dashboard_main.dart
  lib/screens/dashboard/rounded_box.dart
  lib/screens/salon/multi_select.dart
  lib/screens/salon/salon_main.dart
  lib/theme/app_theme.dart
  lib/theme/palette.dart
  lib/widgets/base_drawer.dart
  lib/widgets/bottom_navigation_bar.dart
Labels: 🔨 Chore

#25 Chore: theme.dart内のexportパスの誤字を修正
  lib/theme/theme.dart
Labels: 🔨 Chore
